### ISSUE TITLE
Rich Presence is dropped if executable is in detectables.json(?)

### ISSUE THREAD

**Issue by mynnshaw** [SpikeHD/rsRPC#8] opened 2024-12-20 23:54 UTC
I struggled to figure a way to write the title, sorry about that. This may be related to #3 but unconfirmed.

In a use case where a game has both a Rich Presence using Game SDK and an entry in detectable.json, it seems the generic detectable.json entry is chosen, showing the game name but showing no details. The Game SDK rich presence seems to be dropped and is treated as though it's not detected at all.

This is handled differently than arRPC, which just chooses to show both implimentations at once. Discord hides the detectable entry when Game SDK rich presence is present, and it seems rsRPC is doing the opposite.

Replicated with the following games:
- Ultrakill
- Payday 2

It seems to be if Rich Presence comes from a game with a detectables.json entry, it drops whatever the Game SDK DLL reports and just goes with the detectables.json entry. I've not tested if this could work if an executable manually added with Registered Games works, just with games that are already detected.

**Comment by mynnshaw** [comment] 2024-12-21 01:06
It seems after I hid detection for ULTRAKILL, turning it back on doesn't restore it anymore (using Dorion's build), so that seems to also be a mild issue.

**Comment by mynnshaw** [comment] 2024-12-21 01:13
Switching to the latest build from issue #7 restored game detection. This issue is still present.

![image](https://github.com/user-attachments/assets/107d9e6c-37ef-483f-80fa-26505e4aa466)

**Comment by mynnshaw** [comment] 2024-12-21 01:16
`[2024-12-20 21:16:12] [Client Connector] Already sent payload for activity: ULTRAKILL`
Might be related?

**Comment by SpikeHD** [comment] 2024-12-21 01:53
I believe this might be related to #3, I am willing to bet you have other stuff doing rich presence which is causing the ULTRAKILL stuff to not show up (like described in that other issue). Since process detection is running separately to IPC detection, it probably is just the only thing that works (therefore giving the illusion that process detection has something to do with it, which I don't think it  does).

I figured this out because I left foobar2k open with rich presence which worked fine, and when opening ULTRAKILL it would handshake but not make it any further. Once I closed foobar2k and restarted rsRPC and ULTRAKILL, the ULTRAKILL presence worked.

I'm gonna call this a dupe of #3 but feel free to add any details there since I still don't know the exact cause :)

**Closed by SpikeHD** 2024-12-21 01:53 UTC
